name: tamam_business
description: Tamam for Business - Multi-vendor platform for restaurants, grocery stores, pharmacies & service providers.
publish_to: 'none'
version: 1.0.26+30

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  firebase_remote_config: ^5.5.0
  flutter_local_notifications: ^17.2.4
  path_provider: ^2.1.4
  url_strategy: ^0.3.0
  shimmer_animation: ^2.2.1
  image_picker: ^1.1.2
  http: ^1.2.2
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.2
  vibration: ^3.1.3
  audioplayers: ^6.5.0
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.8.0
  phone_numbers_parser: ^9.0.0
  country_code_picker: ^3.3.0
  flutter_widget_from_html_core: ^0.17.0
  photo_view: ^0.15.0
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  cached_network_image: ^3.4.1
  print_bluetooth_thermal: ^1.1.5
  flutter_esc_pos_utils: ^1.0.1
  screenshot: ^3.0.0
  http_parser: ^4.1.0
  path: ^1.9.0
  intl: ^0.20.2
  
  google_fonts: ^6.2.1
  image: ^4.2.0
  dotted_border: ^2.1.0
  carousel_slider: ^5.1.1
  just_the_tooltip: ^0.0.12
  flutter_inappwebview: ^6.0.0
  permission_handler: ^12.0.1
  location: ^7.0.0
  flutter_svg: ^2.2.0
  share_plus: ^10.0.2
  card_swiper: ^3.0.1
  file_picker: ^8.3.7
  video_player: ^2.10.0
  chewie: ^1.12.1
  fluttertoast: ^8.2.12
  web_socket_channel: ^2.4.5

  #Rental Module
  dropdown_button2: ^2.3.9
  lottie: ^3.2.0
  syncfusion_flutter_datepicker: ^30.1.41
  flutter_kurdish:
    git: https://github.com/hooshyar/flutter_kurdish

dependency_overrides:
  collection: ^1.19.0
  web: ^1.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/taxi_image/
    - assets/language/
    - assets/notification.mp3
    - assets/json/
    - shorebird.yaml

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900

# Launcher icons configuration - Business App
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/image/logo_business.png
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/image/logo_business.png
  web:
    generate: true
    image_path: assets/image/logo_business.png
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: assets/image/logo_business.png
  macos:
    generate: true
    image_path: assets/image/logo_business.png
  linux:
    generate: true
    image_path: assets/image/logo_business.png

# Native splash screen configuration - REMOVED
# Using custom loading widget in app instead of native splash screen